from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from .utils import clean_filename_part, filename_timestamp


STATUS_FILLS = {
    "Normal": "DCFCE7",
    "High": "FEE2E2",
    "Low": "FEF3C7",
    "Abnormal": "FFE4E6",
    "Critical": "FCA5A5",
    "Unclassified": "E5E7EB",
}


def build_excel_report(dataset: dict[str, Any], generated_by: str) -> tuple[bytes, str]:
    wb = Workbook()
    summary_ws = wb.active
    summary_ws.title = "Report Summary"
    _write_summary(summary_ws, dataset, generated_by)

    _write_table(wb.create_sheet("Consolidated Patient Data"), dataset.get("rows") or [])
    detail_rows = dataset.get("detail_rows") or dataset.get("rows") or []
    _write_table(wb.create_sheet("Parameter-Level Results"), detail_rows)
    _write_table(wb.create_sheet("Abnormal Results"), dataset.get("abnormal_rows") or [])

    tests: dict[str, list[dict[str, Any]]] = {}
    for row in detail_rows:
        test_name = str(row.get("test_name") or "Unknown Test")[:31]
        tests.setdefault(test_name, []).append(row)
    if 1 <= len(tests) <= 10:
        for test_name, rows in tests.items():
            safe_name = _safe_sheet_name(test_name, wb.sheetnames)
            _write_table(wb.create_sheet(safe_name), rows)

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    filters = dataset.get("filters") or {}
    report_part = clean_filename_part(dataset.get("report_name") or "Report")
    filename = (
        f"Patient_Diagnostic_Intelligence_{report_part}_"
        f"{filters.get('from_date', 'NA')}_to_{filters.get('to_date', 'NA')}_{filename_timestamp()}.xlsx"
    )
    return output.getvalue(), filename


def _write_summary(ws, dataset: dict[str, Any], generated_by: str) -> None:
    title_fill = PatternFill("solid", fgColor="1E3A8A")
    sub_fill = PatternFill("solid", fgColor="E2E8F0")
    white = Font(color="FFFFFF", bold=True, size=14)
    bold = Font(bold=True)
    ws.merge_cells("A1:D1")
    ws["A1"] = "Patient Diagnostic Intelligence"
    ws["A1"].fill = title_fill
    ws["A1"].font = white
    ws["A1"].alignment = Alignment(horizontal="center")
    ws.merge_cells("A2:D2")
    ws["A2"] = dataset.get("report_name") or "Diagnostic Report"
    ws["A2"].fill = sub_fill
    ws["A2"].font = bold
    ws["A2"].alignment = Alignment(horizontal="center")

    filters = dataset.get("filters") or {}
    summary = dataset.get("summary") or {}
    rows = [
        ("Generated By", generated_by),
        ("Generated At", datetime.now().strftime("%Y-%m-%d %H:%M:%S")),
        ("Date Range", f"{filters.get('from_date')} to {filters.get('to_date')}"),
        ("Selected Tests", ", ".join(str(x) for x in (filters.get("test_ids") or [])) or "All within filters"),
        ("Result Status", filters.get("result_status", "all")),
        ("Authorization", filters.get("auth_status", "all")),
        ("Total Patients", summary.get("patients_covered", 0)),
        ("Total Tests", summary.get("total_tests_found", 0)),
        ("Total Abnormal Results", summary.get("abnormal_results", 0)),
        ("Follow-up Candidates", summary.get("followup_candidates", 0)),
        ("Reportable Records", summary.get("reportable_records", 0)),
    ]
    if dataset.get("export_note"):
        rows.append(("Export Note", dataset.get("export_note")))
    start = 4
    for idx, (label, value) in enumerate(rows, start=start):
        ws.cell(idx, 1, label).font = bold
        ws.cell(idx, 2, value)
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 42


def _write_table(ws, rows: list[dict[str, Any]]) -> None:
    thin = Side(style="thin", color="CBD5E1")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_fill = PatternFill("solid", fgColor="1E3A8A")
    alt_fill = PatternFill("solid", fgColor="F8FAFC")
    header_font = Font(color="FFFFFF", bold=True)
    if not rows:
        ws["A1"] = "No records found"
        ws["A1"].font = Font(bold=True, color="64748B")
        ws.column_dimensions["A"].width = 24
        return
    headers = _ordered_headers(rows[0])
    for col, header in enumerate(headers, start=1):
        cell = ws.cell(1, col, _label(header))
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border
    for row_idx, row in enumerate(rows, start=2):
        status = str(row.get("result_status") or row.get("last_result_status") or "")
        for col_idx, key in enumerate(headers, start=1):
            cell = ws.cell(row_idx, col_idx, row.get(key))
            cell.border = border
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            if row_idx % 2 == 0:
                cell.fill = alt_fill
            if key in {"result_status", "last_result_status"} and status in STATUS_FILLS:
                cell.fill = PatternFill("solid", fgColor=STATUS_FILLS[status])
                cell.font = Font(bold=True)
    ws.freeze_panes = "A2"
    for idx, header in enumerate(headers, start=1):
        max_len = len(_label(header))
        for row in rows[:500]:
            max_len = max(max_len, len(str(row.get(header) or "")[:60]))
        ws.column_dimensions[get_column_letter(idx)].width = min(max(max_len + 2, 12), 42)
    ws.auto_filter.ref = ws.dimensions


def _label(key: str) -> str:
    return str(key).replace("_", " ").title()


def _ordered_headers(sample: dict[str, Any]) -> list[str]:
    hidden = {
        "authorization_status",
        "result_auth_flag",
        "result_auth_by",
        "result_auth_datetime",
        "rn",
        "total_rows",
        "patient_id",
        "visit_id",
        "order_id",
        "sample_id",
        "service_id",
        "service_category_id",
        "test_id",
        "parameter_id",
        "param_low",
        "param_high",
        "machine_name",
        "sample_accept_datetime",
    }
    preferred = [
        "patient_name", "registration_no", "patient_age", "mobile", "visit_no", "visit_date",
        "visit_type", "patient_type", "patient_subtype", "test_name", "parameter_name", "result", "unit", "normal_range",
        "low_value", "high_value", "result_status", "doctor_name", "suggested_action",
        "suggested_followup_reason", "priority", "days_since_last_test",
    ]
    keys = [key for key in preferred if key in sample and key not in hidden]
    keys.extend([key for key in sample.keys() if key not in hidden and key not in keys])
    return keys


def _safe_sheet_name(name: str, existing: list[str]) -> str:
    invalid = set(r'[]:*?/\\')
    base = "".join("_" if ch in invalid else ch for ch in str(name or "Sheet"))[:31].strip() or "Sheet"
    candidate = base
    idx = 2
    while candidate in existing:
        suffix = f"_{idx}"
        candidate = (base[: 31 - len(suffix)] + suffix).strip()
        idx += 1
    return candidate
