from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from xml.sax.saxutils import escape

from .utils import PDF_ROW_LIMIT, clean_filename_part, filename_timestamp


def build_pdf_report(dataset: dict[str, Any], generated_by: str) -> tuple[bytes, str]:
    rows = dataset.get("rows") or []
    if len(rows) > PDF_ROW_LIMIT:
        raise ValueError(f"PDF row limit is {PDF_ROW_LIMIT}. Please use Excel for large detailed exports.")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        topMargin=12 * mm,
        bottomMargin=12 * mm,
        leftMargin=10 * mm,
        rightMargin=10 * mm,
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle("PDITitle", parent=styles["Heading2"], alignment=TA_CENTER, textColor=colors.HexColor("#1e3a8a"), fontSize=13)
    meta = ParagraphStyle("PDIMeta", parent=styles["Normal"], alignment=TA_CENTER, textColor=colors.HexColor("#475569"), fontSize=8)
    cell = ParagraphStyle("PDICell", parent=styles["Normal"], fontSize=6.5, leading=8, wordWrap="CJK")
    head = ParagraphStyle("PDIHead", parent=styles["Normal"], fontSize=7, textColor=colors.white, alignment=TA_CENTER)

    filters = dataset.get("filters") or {}
    elements = [
        Paragraph("ASARFI HOSPITAL - Patient Diagnostic Intelligence", title),
        Paragraph(escape(str(dataset.get("report_name") or "Diagnostic Report")), title),
        Paragraph(
            escape(f"Date Range: {filters.get('from_date')} to {filters.get('to_date')} | Generated By: {generated_by} | Generated At: {datetime.now():%Y-%m-%d %H:%M:%S}"),
            meta,
        ),
        Spacer(1, 6),
    ]
    summary = dataset.get("summary") or {}
    summary_rows = [
        ["Patients", summary.get("patients_covered", 0), "Abnormal", summary.get("abnormal_results", 0), "Records", summary.get("reportable_records", len(rows))],
        ["Selected Tests", summary.get("selected_tests_count", 0), "Authorized", summary.get("authorized_reports", 0), "Pending", summary.get("pending_authorization_reports", 0)],
    ]
    summary_table = Table(summary_rows, colWidths=[30 * mm, 22 * mm, 30 * mm, 22 * mm, 30 * mm, 22 * mm])
    summary_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CBD5E1")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 8))
    elements.append(_table(rows, head, cell))

    def page_number(canvas, doc_obj):
        canvas.saveState()
        width, _height = doc.pagesize
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(10 * mm, 7 * mm, "System generated diagnostic intelligence report")
        canvas.drawRightString(width - 10 * mm, 7 * mm, f"Page {doc_obj.page}")
        canvas.restoreState()

    doc.build(elements, onFirstPage=page_number, onLaterPages=page_number)
    buffer.seek(0)
    report_part = clean_filename_part(dataset.get("report_name") or "Report")
    filename = (
        f"Patient_Diagnostic_Intelligence_{report_part}_"
        f"{filters.get('from_date', 'NA')}_to_{filters.get('to_date', 'NA')}_{filename_timestamp()}.pdf"
    )
    return buffer.getvalue(), filename


def _table(rows: list[dict[str, Any]], head_style, cell_style) -> Table:
    if not rows:
        return Table([[Paragraph("No records found", cell_style)]], colWidths=[260 * mm])
    preferred = [
        "patient_name", "registration_no", "patient_age", "mobile", "visit_date", "test_name",
        "parameter_name", "result", "unit", "normal_range", "result_status",
        "doctor_name", "suggested_action",
    ]
    keys = [k for k in preferred if k in rows[0]]
    if not keys:
        keys = list(rows[0].keys())[:10]
    keys = keys[:12]
    data = [[Paragraph(_label(k), head_style) for k in keys]]
    for row in rows:
        data.append([Paragraph(escape(str(row.get(k) or "")), cell_style) for k in keys])
    col_width = (277 * mm) / max(len(keys), 1)
    table = Table(data, colWidths=[col_width] * len(keys), repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    return table


def _label(key: str) -> str:
    return str(key).replace("_", " ").title()
